aws:
  region: ap-northeast-1
  ml_bucket: s3://ml-bucket
  gga_bucket: s3://raw-data-buckey
  ssm_cloud_sql_info: /cloud-sql/ssm
  ssm_gcp_service_account: /gcp-service-account/ssm

gcp:
  project_id: gcp-project-id
  ml_bucket: gs://ml-bucket

gcp_data_transfer:
  aws_s3_data_source: ml-data-on-aws
  gcs_data_source: ml-data-on-gcp
  timeout: 10800

airflow_connection_ids:
  slack_conn_id: airflow-slack
  aws_conn_id: airflow-ml-aws
  gcp_conn_id: airflow-gcp-conn
  gcp_cloud_sql_conn_id: airflow-ml-cloud-sql-conn
  gcp_data_transfer_conn_id: airflow-aws-gcp-datatransfer
  ml_slack: 
    conn_id: airflow-ml-slack
    post_channel: "#airflow-alerts"
